import crypto from 'crypto';
import { desc, and, gte } from 'drizzle-orm';
import { db } from '../database.js';
import { autoHealLog } from '../schema/events.js';
import { runHealthCheck, persistHealthCheck, type HealthCheckResult, type HealthCheckItem } from './health-checker.service.js';
import { createAlert } from './alert.service.js';
import { isEnabled } from './feature.service.js';
import { logger } from '../utils/logger.js';

// ── Types ──────────────────────────────────────────────────────────────────

export interface HealRule {
  id: string;
  name: string;
  condition: (checks: HealthCheckItem[], result: HealthCheckResult) => boolean;
  action: HealAction;
  cooldownMs: number;
  maxExecutions: number;
  requiresConfirmation: boolean;
  enabled: boolean;
}

export type HealAction =
  | { type: 'send_alert'; severity: string; message: string }
  | { type: 'log_only'; message: string };

// ── Execution Tracking ─────────────────────────────────────────────────────

const executionLog = new Map<string, { count: number; lastAt: number; windowStart: number }>();
const COOLDOWN_WINDOW_MS = 3600_000; // 1 hour rolling window

function isInCooldown(rule: HealRule): boolean {
  const log = executionLog.get(rule.id);
  if (!log) return false;
  return Date.now() - log.lastAt < rule.cooldownMs;
}

function exceedsRateLimit(rule: HealRule): boolean {
  const log = executionLog.get(rule.id);
  if (!log) return false;
  // Reset window if expired
  if (Date.now() - log.windowStart > COOLDOWN_WINDOW_MS) {
    executionLog.set(rule.id, { count: 0, lastAt: log.lastAt, windowStart: Date.now() });
    return false;
  }
  return log.count >= rule.maxExecutions;
}

function recordExecution(ruleId: string): void {
  const log = executionLog.get(ruleId);
  const now = Date.now();
  if (!log || now - log.windowStart > COOLDOWN_WINDOW_MS) {
    executionLog.set(ruleId, { count: 1, lastAt: now, windowStart: now });
  } else {
    log.count++;
    log.lastAt = now;
  }
}

// ── Heal Rules ─────────────────────────────────────────────────────────────

const HEAL_RULES: HealRule[] = [
  {
    id: 'pg_connectivity_fail',
    name: '数据库连接失败告警',
    condition: (checks) => checks.some(c => c.name === 'pg_connectivity' && c.status === 'fail'),
    action: { type: 'send_alert', severity: 'critical', message: '数据库连接失败，需要立即处理' },
    cooldownMs: 300_000,
    maxExecutions: 3,
    requiresConfirmation: false,
    enabled: true,
  },
  {
    id: 'redis_connectivity_fail',
    name: 'Redis 连接失败告警',
    condition: (checks) => checks.some(c => c.name === 'redis_connectivity' && c.status === 'fail'),
    action: { type: 'send_alert', severity: 'high', message: 'Redis 连接失败，已降级到内存缓存' },
    cooldownMs: 300_000,
    maxExecutions: 3,
    requiresConfirmation: false,
    enabled: true,
  },
  {
    id: 'event_bus_backlog_clear',
    name: '事件总线积压告警',
    condition: (checks) => checks.some(c => c.name === 'event_bus_backlog' && c.status === 'fail'),
    action: { type: 'send_alert', severity: 'high', message: '事件总线积压超限，需要排查消费者' },
    cooldownMs: 300_000,
    maxExecutions: 2,
    requiresConfirmation: false,
    enabled: true,
  },
  {
    id: 'memory_high',
    name: '内存使用告警',
    condition: (checks) => checks.some(c => c.name === 'memory_usage' && c.status === 'fail'),
    action: { type: 'send_alert', severity: 'high', message: '内存使用超过 90%，需要关注' },
    cooldownMs: 600_000,
    maxExecutions: 3,
    requiresConfirmation: false,
    enabled: true,
  },
  {
    id: 'event_loop_slow',
    name: '事件循环延迟告警',
    condition: (checks) => checks.some(c => c.name === 'event_loop_lag' && c.status === 'fail'),
    action: { type: 'send_alert', severity: 'medium', message: '事件循环延迟过高，可能存在阻塞操作' },
    cooldownMs: 600_000,
    maxExecutions: 3,
    requiresConfirmation: false,
    enabled: true,
  },
  // NOTE: system_unhealthy rule removed — it duplicated the alert already generated by
  // the system.health.degraded event emitted from health-checker.service.ts runHealthCheck().
  // Having both caused 2 alerts per unhealthy tick (one from event→alert rule, one from heal rule).
];

// ── Execute Heal Action ────────────────────────────────────────────────────

async function executeAction(rule: HealRule, result: HealthCheckResult): Promise<void> {
  const id = crypto.randomUUID();

  try {
    switch (rule.action.type) {
      case 'send_alert':
        await createAlert({
          tenantId: 'system',
          severity: rule.action.severity as any,
          category: 'system',
          title: rule.name,
          description: rule.action.message,
          metadata: { ruleId: rule.id, healthScore: result.score },
        });
        break;

      case 'log_only':
        logger.info(`Auto-heal [${rule.id}]: ${rule.action.message}`);
        break;
    }

    // Log success
    await db.insert(autoHealLog).values({
      id,
      ruleId: rule.id,
      ruleName: rule.name,
      actionType: rule.action.type,
      actionParams: JSON.stringify(rule.action),
      status: 'success',
      executedBy: 'system',
    });

    recordExecution(rule.id);
    logger.info(`Auto-heal executed: ${rule.name}`, { ruleId: rule.id });

  } catch (err: any) {
    logger.error(`Auto-heal failed: ${rule.name}`, { error: err.message });
    await db.insert(autoHealLog).values({
      id,
      ruleId: rule.id,
      ruleName: rule.name,
      actionType: rule.action.type,
      actionParams: JSON.stringify(rule.action),
      status: 'failed',
      error: err.message,
      executedBy: 'system',
    });
  }
}

// ── Main Tick ──────────────────────────────────────────────────────────────

/** Main auto-heal loop — called by scheduler every AUTO_HEAL_TICK_INTERVAL_MS */
export async function autoHealTick(): Promise<void> {
  // Check if auto-heal is enabled via the feature toggle system
  if (!isEnabled('autoHeal')) {
    logger.debug('Auto-heal is disabled via the autoHeal feature flag');
    return;
  }

  try {
    const result = await runHealthCheck();

    // Persist health check result (fixes: scheduler runs weren't being recorded)
    await persistHealthCheck(result);

    for (const rule of HEAL_RULES) {
      if (!rule.enabled) continue;
      if (!rule.condition(result.checks, result)) continue;
      if (isInCooldown(rule)) continue;
      if (exceedsRateLimit(rule)) continue;

      await executeAction(rule, result);
    }
  } catch (err: any) {
    logger.error(`Auto-heal tick failed: ${err.message}`);
  }
}

/** Get auto-heal execution log */
export async function getAutoHealLog(hours: number = 24): Promise<Array<{
  ruleId: string;
  ruleName: string;
  actionType: string;
  status: string;
  error?: string;
  executedAt: Date;
}>> {
  const since = new Date(Date.now() - hours * 3600_000);
  const rows = await db.select()
    .from(autoHealLog)
    .where(gte(autoHealLog.executedAt, since))
    .orderBy(desc(autoHealLog.executedAt))
    .limit(100);

  return rows.map(r => ({
    ruleId: r.ruleId,
    ruleName: r.ruleName,
    actionType: r.actionType,
    status: r.status,
    error: r.error ?? undefined,
    executedAt: r.executedAt!,
  }));
}

/** Get list of all heal rules with their enabled status */
export function getHealRules(): Array<{ id: string; name: string; enabled: boolean; requiresConfirmation: boolean }> {
  return HEAL_RULES.map(r => ({
    id: r.id,
    name: r.name,
    enabled: r.enabled,
    requiresConfirmation: r.requiresConfirmation,
  }));
}

/** Update a heal rule's enabled status */
export function updateHealRule(ruleId: string, enabled: boolean): boolean {
  const rule = HEAL_RULES.find(r => r.id === ruleId);
  if (!rule) return false;
  rule.enabled = enabled;
  return true;
}
