/**
 * Canonical audit action names. Before this existed, actions were a mix of SCREAMING_SNAKE
 * (most of the codebase) and admin_snake_case (server/routes/admin.ts only) — that split
 * made filtering/reporting on "all admin actions" or exporting a consistent CSV needlessly
 * hard. Every logAudit() call site should reference one of these constants rather than a
 * string literal.
 */
export const AuditAction = {
  // Auth
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_FAILED_MFA: 'LOGIN_FAILED_MFA',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  EMAIL_VERIFICATION_RESENT: 'EMAIL_VERIFICATION_RESENT',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE: 'PASSWORD_RESET_COMPLETE',
  PASSWORD_CHANGED_EXPIRED: 'PASSWORD_CHANGED_EXPIRED',
  PASSWORD_FORCE_CHANGED: 'PASSWORD_FORCE_CHANGED',
  PASSWORD_CHANGE_FAILED: 'PASSWORD_CHANGE_FAILED',
  PASSWORD_CHANGE_SUCCESS: 'PASSWORD_CHANGE_SUCCESS',
  OTP_ENABLED: 'OTP_ENABLED',

  // MFA
  MFA_FACTOR_ENABLED: 'MFA_FACTOR_ENABLED',
  MFA_FACTOR_DISABLED: 'MFA_FACTOR_DISABLED',
  MFA_RECOVERY_CODES_GENERATED: 'MFA_RECOVERY_CODES_GENERATED',

  // Federation
  GITHUB_LOGIN_SUCCESS: 'GITHUB_LOGIN_SUCCESS',
  GITHUB_LOGIN_FAILED: 'GITHUB_LOGIN_FAILED',
  FEDERATION_LOGIN_SUCCESS: 'FEDERATION_LOGIN_SUCCESS',
  FEDERATION_LOGIN_FAILED: 'FEDERATION_LOGIN_FAILED',
  IDP_CREATED: 'IDP_CREATED',
  IDP_UPDATED: 'IDP_UPDATED',
  IDP_DELETED: 'IDP_DELETED',

  // OAuth/OIDC
  OAUTH_AUTHORIZE: 'OAUTH_AUTHORIZE',
  OAUTH_DEVICE_APPROVE: 'OAUTH_DEVICE_APPROVE',
  OAUTH_DEVICE_DENY: 'OAUTH_DEVICE_DENY',
  OAUTH_END_SESSION: 'OAUTH_END_SESSION',

  // User self-service
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  TRUSTED_DEVICE_REVOKED: 'TRUSTED_DEVICE_REVOKED',
  ACCOUNT_DELETION_REQUESTED: 'ACCOUNT_DELETION_REQUESTED',
  ACCOUNT_DELETION_CANCELLED: 'ACCOUNT_DELETION_CANCELLED',
  AVATAR_UPLOADED: 'AVATAR_UPLOADED',
  AVATAR_URL_SET: 'AVATAR_URL_SET',
  AVATAR_DELETED: 'AVATAR_DELETED',
  DATA_EXPORT_REQUESTED: 'DATA_EXPORT_REQUESTED',

  // Admin — user management (was admin_snake_case)
  ADMIN_USER_CREATE: 'ADMIN_USER_CREATE',
  ADMIN_USER_UPDATE: 'ADMIN_USER_UPDATE',
  ADMIN_USER_DELETE: 'ADMIN_USER_DELETE',
  ADMIN_USER_BAN: 'ADMIN_USER_BAN',
  ADMIN_USER_UNBAN: 'ADMIN_USER_UNBAN',
  ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',

  // Admin — client management
  ADMIN_CLIENT_CREATE: 'ADMIN_CLIENT_CREATE',
  ADMIN_CLIENT_UPDATE: 'ADMIN_CLIENT_UPDATE',
  ADMIN_CLIENT_DELETE: 'ADMIN_CLIENT_DELETE',
  ADMIN_CLIENT_SECRET_ROTATE: 'ADMIN_CLIENT_SECRET_ROTATE',

  // Admin — tenant / session / IP whitelist
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DELETE: 'TENANT_DELETE',
  ADMIN_SESSION_REVOKED: 'ADMIN_SESSION_REVOKED',
  IP_WHITELIST_ADDED: 'IP_WHITELIST_ADDED',
  IP_WHITELIST_REMOVED: 'IP_WHITELIST_REMOVED',
  IP_BLOCKED: 'IP_BLOCKED',

  // SCIM
  SCIM_USER_CREATED: 'SCIM_USER_CREATED',
  SCIM_USER_UPDATED: 'SCIM_USER_UPDATED',
  SCIM_USER_PATCHED: 'SCIM_USER_PATCHED',
  SCIM_USER_DEACTIVATED: 'SCIM_USER_DEACTIVATED',
  SCIM_GROUP_CREATED: 'SCIM_GROUP_CREATED',
  SCIM_GROUP_UPDATED: 'SCIM_GROUP_UPDATED',
  SCIM_GROUP_PATCHED: 'SCIM_GROUP_PATCHED',
  SCIM_GROUP_DELETED: 'SCIM_GROUP_DELETED',

  // Compliance
  AUDIT_LOG_EXPORTED: 'AUDIT_LOG_EXPORTED',
  AUDIT_LOG_VERIFIED: 'AUDIT_LOG_VERIFIED',
  COMPLIANCE_REPORT_GENERATED: 'COMPLIANCE_REPORT_GENERATED',
} as const;

export type AuditActionName = typeof AuditAction[keyof typeof AuditAction];

/** Actions that represent a privileged/administrative operation — used by the compliance report. */
export const PRIVILEGED_ACTIONS: readonly AuditActionName[] = [
  AuditAction.ADMIN_USER_CREATE, AuditAction.ADMIN_USER_UPDATE, AuditAction.ADMIN_USER_DELETE,
  AuditAction.ADMIN_USER_BAN, AuditAction.ADMIN_USER_UNBAN, AuditAction.ADMIN_PASSWORD_RESET,
  AuditAction.ADMIN_CLIENT_CREATE, AuditAction.ADMIN_CLIENT_UPDATE, AuditAction.ADMIN_CLIENT_DELETE,
  AuditAction.ADMIN_CLIENT_SECRET_ROTATE, AuditAction.TENANT_CREATE, AuditAction.TENANT_UPDATE,
  AuditAction.TENANT_DELETE, AuditAction.ADMIN_SESSION_REVOKED, AuditAction.IP_WHITELIST_ADDED,
  AuditAction.IP_WHITELIST_REMOVED, AuditAction.IDP_CREATED, AuditAction.IDP_UPDATED, AuditAction.IDP_DELETED,
];

/** Actions that represent an anomaly/security-relevant event — used by the compliance report. */
export const ANOMALY_ACTIONS: readonly AuditActionName[] = [
  AuditAction.LOGIN_FAILED, AuditAction.LOGIN_FAILED_MFA, AuditAction.IP_BLOCKED,
  AuditAction.GITHUB_LOGIN_FAILED, AuditAction.FEDERATION_LOGIN_FAILED, AuditAction.PASSWORD_CHANGE_FAILED,
];
